image: "git-docker-classes.mst.edu/containers/container"

variables:
  IS_IN_DOCKER: 1

generaltester:
  script:
  - bash grade.sh
  timeout: 2 hours 30 minutes
  artifacts:
    when: always
    paths:
      - results.txt
    expire_in: 1 month
